### ISSUE TITLE
How to use this with angular 2 app + web api

### ISSUE THREAD

**Issue by djoyrocks** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#11]
How to use azure b2c with angular 2 app + web api

**Comment by cartyd** [comment]
Did you get an answer for this?

**Comment by Prashant89Chaudhary** [comment]
Hi I am getting an exception during build of project in OpenIdConnectCachingSecurityTokenProvider.cs while running below code.

`OpenIdConnectConfiguration config = Task.Run(_configManager.GetConfigurationAsync).Result;`

Exception : 
The call is ambiguous between the following methods or properties: 'System.Threading.Tasks.Task.Run<Microsoft.IdentityModel.Protocols.OpenIdConnectConfiguration>(System.Func<System.Threading.Tasks.Task<Microsoft.IdentityModel.Protocols.OpenIdConnectConfiguration>>)' and 'System.Threading.Tasks.Task.Run(System.Action)'

**Comment by CharlBest** [comment]
I'm also trying to add Azure B2C with my Angular 4 app (client) with an .NET Core Web Api app (backend) but not sure if it will work and if its going to be reliable and secure? Any advise or suggestions?

**Comment by gsacavdm** [comment]
I'm closing this as this isn't an issue with this sample.
I'd encourage you guys to add a feedback entry to the [Azure AD B2C feedback forum].(https://feedback.azure.com/forums/169401-azure-active-directory/category/160596-b2c)
