### ISSUE TITLE
Using localStorage directly causing issues.

### ISSUE THREAD

**Issue by last1here** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#12]
The [fixes](https://github.com/Azure-Samples/active-directory-b2c-javascript-singlepageapp-dotnet-webapi/blob/master/B2C-v2jsapp/scripts/hello.all.js#L553) used to store the state between B2C and the app causes issues in certain circumstances because of it use of `localStorage` directly. For instance on iOS when an incognito tab is used. A solution that I have found works is to use the `hello.utils.store` function which checks the access to the storage before use and falls back to cookies when required. I will be happy to submit a PR if this is seen as the correct solution.

**Comment by getsetbro** [comment]
Please make the PR.

**Comment by gsacavdm** [comment]
This should no longer be an issue since we no longer have the modifications on hello.js.
