### ISSUE TITLE
Backend code

### ISSUE THREAD

**Issue by thomasdc** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#15]
Thanks for this example. However, I'm curious about the backend code of https://fabrikamb2chello.azurewebsites.net.

Would you mind including this in the repo as well?

**Comment by gsacavdm** [comment]
Hi @thomasdc, the code for https://fabrikamb2chello.azurewebsites.net is the same as our [Node.js Web API with Azure AD B2C](https://github.com/Azure-Samples/active-directory-b2c-javascript-nodejs-webapi) . I'll update the readme to indicate so.
