### ISSUE TITLE
Implement forgot password scenario

### ISSUE THREAD

**Issue by DibranMulder** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#18]
When using a combined signup - signin policy in Azure B2C, users have to handle the forgot password scenario themselves. Please take a look at the documentation.

> How do I link a sign-up or sign-in policy with a password reset policy?
> When you create a sign-up or sign-in policy (with local accounts), you see a Forgot password? link on the first page of the experience. Clicking this link doesn't automatically trigger a password reset policy.
> Instead, the error code AADB2C90118 is returned to your app. Your app needs to handle this error code by invoking a specific password reset policy. For more information, see a sample that demonstrates the approach of linking policies.

I would be nice if this example included that scenario.

**Comment by LTrain** [comment]
Agreed - thank you for calling it out

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp
