### ISSUE TITLE
Logout button in SUSI policy does not log out.

### ISSUE THREAD

**Issue by John-Garland** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#2]
When I configure and subsequently run the project, then select "Sign-In or Sign-Up Policy Login", use the buttons to do some POST and GET calls, then use the "Sign-Up or Sign-In Policy Logout" button, it refreshes the screen and clears the text, but I am still able to make subsequent calls to GET and POST (via the same buttons) continue to succeed.
Using breakpoints in the Get/Post methods, the breakpoints are still hit, indicating the call is still making it through the Authorization filter (and the ClaimsPrincipal still has a value.)

**Comment by rajanikanthr** [comment]
it's now updated to remove token from hellojs local storage while logout. previously even after logout, GET and POST calls were possible until the token expiry.
