### ISSUE TITLE
CORS Issue

### ISSUE THREAD

**Issue by LTrain** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#22]
I've implemented the scenario as described but when I attempt to use the "Call API" button I get 
"API error: Could not get resource". Looking through the browser log I noticed a CORS error:

index.html:1 Failed to load <Web API URL>: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:65328' is therefore not allowed access. The response had HTTP status code 400.

This is strange because I included http://localhost:65328/ and * in my CORS rules for the WebAPI. 
Any ideas?

**Comment by gsacavdm** [comment]
Where and how did you configure your CORS rules?

**Comment by LTrain** [comment]
In the function Apps section of the portal.  We selected CORS from the API section and listed our localhost. 
(Actually I listed * but that didn't have an effect either)

**Comment by LTrain** [comment]
Pilot error I added a trailing slash to the Localhost configuration.
