### ISSUE TITLE
Invoking password reset

### ISSUE THREAD

**Issue by LTrain** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#23]
Can you post a code snippet on how to invoke the password reset UI using hellojs and B2C. 
We are detecting error AADB2C90118 now - but need sample code on actually triggering the reset UI.

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp
