### ISSUE TITLE
Twitter provider doesn't work with popup

### ISSUE THREAD

**Issue by vladkosarev** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#24]
If we use popup instead of page then Twitter provider stops working. This issue also happens with MSAL. Is there any way to deal with that in any of the available libraries?

Thanks.

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp
