### ISSUE TITLE
Doesn't work AT ALL

### ISSUE THREAD

**Issue by kwaazaar** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#25]
This sample does not work at all. I can log in, but when coming back to the app, it shows the starting page again, as if I'm not logged in. It does not matter whether I log in using username/pwd or social login.

**Comment by leniel** [comment]
I'm just experiencing this right now... after the login process, it goes to the redirect.html and then back to the index.html page. Nothing is happening. API Response and Auth Response are empty.

Hello @parakhj or @jmprieur can you help?

I know the code is 2 years old right now... if it doesn't work anymore, can you provide an updated sample?

**Comment by leniel** [comment]
I guess this is the way to go today:

https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp

**Comment by derisen** [comment]
Closing this issue as the sample is archived. Please refer to this sample: https://github.com/Azure-Samples/active-directory-b2c-javascript-msal-singlepageapp
