### ISSUE TITLE
Add explanation/introduction to Hello.js in the "ReadMe"

### ISSUE THREAD

**Issue by John-Garland** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#3]
Not being previously familiar with Hello.js, it didn't strike me that it was a 3rd party library you were choosing to employ, where it was sourced from, and where I could go to read/learn more about the proper protocol for calling it. That became obvious after diving through the code, but it is perhaps worthy of a small header and paragraph in the ReadMe file to explicitly call attention to it.

**Comment by John-Garland** [comment]
I would also add - indicate "acceptable versions" and/or if the included 3 js files are "stock" or otherwise altered in any way.

**Comment by rajanikanthr** [comment]
Added introduction to HelloJS and also documented fixes made to make the library work with AD B2C
