### ISSUE TITLE
Mixup with ClientID and TenantId in the Readme instructions

### ISSUE THREAD

**Issue by John-Garland** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#4]
In [Step 5](https://github.com/Azure-Samples/active-directory-b2c-javascript-singlepageapp-dotnet-webapi#step-5-configure-the-sample-to-use-your-b2c-tenant), the second code block is prefaced by the instruction:

> open the aadb2c.js and replace the clientId and policy names

Note that this should be 

> open the aadb2c.js and replace the tenantName and policy names

**Comment by rajanikanthr** [comment]
updated readme to reflect the correct names
