### ISSUE TITLE
Clarify Application ID vs Client ID in the ReadMe How-To instructions

### ISSUE THREAD

**Issue by John-Garland** [Azure-Samples/active-directory-b2c-javascript-hellojs-singlepageapp#5]
In [Step 4](https://github.com/Azure-Samples/active-directory-b2c-javascript-singlepageapp-dotnet-webapi#step-4-create-your-own-application) it states:

> Copy the client ID generated for your application, so you can use it in the next step.

Note that the Azure Portal B2C blades refer to the "client ID" value as "Application ID"

**Comment by rajanikanthr** [comment]
updated in readme, SPA app and TaskService to reflect Application ID everywhere
